# Use custom format
format = """
(light blue)$directory$git_branch$git_status$git_commit$rust$package
$time[â¯](bold green) """


scan_timeout = 10


add_newline = false

[git_branch]
symbol = "ï„¦ "
[git_status]
conflicted = "ï€"
ahead = "ğŸ"
behind = "ï‚¨"
diverged = "ğŸ˜µ"
untracked = "ğŸ¤·â€"
stashed = "ğŸ“¦"
modified = "ï€"
staged = '[++\($count\)](green)'
renamed = ""
deleted = "xxx"

[git_commit]
commit_hash_length = 4
